import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {createKart,createCircuit,palette} from './scene.mjs';
const scene=new T.Scene();scene.background=new T.Color(0xe6e5df);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;document.body.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(38,innerWidth/innerHeight,.02,1800),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xe4edf5,0x716954,2.3));const sun=new T.DirectionalLight(0xfff0da,3.8);sun.position.set(-3,6,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-2;sun.shadow.camera.right=2;sun.shadow.camera.top=2;sun.shadow.camera.bottom=-2;sun.shadow.bias=-.00003;sun.shadow.normalBias=.015;scene.add(sun);
const kart=createKart(),circuit=createCircuit();scene.add(kart,circuit);circuit.visible=false;
const floor=new T.Mesh(new T.PlaneGeometry(2000,2000),new T.MeshStandardMaterial({color:0xe0e0d7,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.012;floor.receiveShadow=true;scene.add(floor);
const parts=kart.userData.parts;const select=document.querySelector('#part');for(const name of Object.keys(parts)){const o=document.createElement('option');o.value=name;o.textContent=name;select.append(o);}
let mode='kart';
function reset(){if(mode==='kart'){camera.position.set(2.5,1.7,-3.2);controls.target.set(0,.25,0);controls.minDistance=1;controls.maxDistance=8;sun.position.set(-3,6,4);sun.shadow.normalBias=.015;sun.shadow.camera.left=-2;sun.shadow.camera.right=2;sun.shadow.camera.top=2;sun.shadow.camera.bottom=-2;}else{camera.position.set(-230,210,-270);controls.target.set(0,0,-15);controls.minDistance=20;controls.maxDistance=750;sun.position.set(-160,240,-110);sun.shadow.normalBias=.5;sun.shadow.camera.left=-240;sun.shadow.camera.right=240;sun.shadow.camera.top=220;sun.shadow.camera.bottom=-220;}camera.near=mode==="kart"?.02:2;camera.updateProjectionMatrix();sun.shadow.camera.updateProjectionMatrix();controls.update();}
function switchMode(next){mode=next;kart.visible=mode==='kart';circuit.visible=mode==='circuit';floor.visible=mode==='kart';scene.fog=mode==='circuit'?new T.Fog(0xe6e5df,550,1100):null;for(const id of ['kart','circuit'])document.getElementById(id).classList.toggle('active',id===mode);for(const id of ['part','explode','paint'])document.getElementById(id).disabled=mode!=='kart';document.querySelector('#title').textContent=mode==='kart'?'Built for the first corner.':'Where the journey begins.';document.querySelector('#description').textContent=mode==='kart'?'A 125cc racing kart concept. Inspect the exposed mechanics, change the livery, and explore our first venue.':'South Garda, Italy · A first circuit art blockout with a paddock, garages, grandstand and Mediterranean surroundings.';document.querySelector('#metric1').innerHTML=mode==='kart'?'125 cc<small>TWO-STROKE ENGINE</small>':Math.round(circuit.userData.routeLength)+' m<small>CONCEPT ROUTE LENGTH</small>';document.querySelector('#metric2').innerHTML=mode==='kart'?'4 slicks<small>RACING TIRES</small>':'9 m<small>TRACK WIDTH</small>';document.querySelector('#metric3').innerHTML=mode==='kart'?'32 mm<small>STEEL FRAME CONCEPT</small>':'Italy<small>FIRST KARTING VENUE</small>';reset();}
document.querySelector('#kart').onclick=()=>switchMode('kart');document.querySelector('#circuit').onclick=()=>switchMode('circuit');document.querySelector('#reset').onclick=reset;
document.querySelector('#paint').oninput=e=>palette.Fairing.color.set(e.target.value);
select.onchange=()=>{for(const [name,g]of Object.entries(parts))g.visible=!select.value||select.value===name;};
document.querySelector('#explode').oninput=e=>{const v=Number(e.target.value);Object.values(parts).forEach((g,i)=>{g.position.y=v*i*.22;});};
const texture=new T.TextureLoader().load('./assets/asphalt_track_diff_1k.jpg',()=>{texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(1,1);texture.anisotropy=renderer.capabilities.getMaxAnisotropy();palette.Asphalt.color.set(0xffffff);palette.Asphalt.map=texture;palette.Asphalt.needsUpdate=true;},undefined,()=>{document.querySelector('#status').textContent='Asphalt texture unavailable';});
reset();document.querySelector('#status').textContent='Drag to inspect · All assets loaded locally';
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
let prev=performance.now();renderer.setAnimationLoop(()=>{const now=performance.now(),dt=Math.min((now-prev)/1000,.05);prev=now;if(document.querySelector('#spin').checked&&mode==='kart')kart.rotation.y+=dt*.25;controls.update();renderer.render(scene,camera);});
window.kartLab={scene,kart,circuit,camera,renderer,controls,switchMode};
